name: Update stats
on:
  schedule:
    - cron: "0 0 * * *" # Diário
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate SVG
        uses: readme-tools/github-readme-stats-action@v1
        with:
          token: ${{ secrets.GH_TOKEN }}
          # O arquivo será salvo localmente
          path: profile/stats.svg
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/stats.svg
          git commit -m "Update stats" || exit 0
          git push
